更新日: 2025-05-25  (Deep-Link & ライブルーム拡張を反映)

サービス概要:
  サービス名: "目醒め人のためのSNS"
  コンセプト: |
    “目醒め” をテーマに、音声を主軸とした深い共感・学び合い・自己表現を促す
    コミュニティSNS。Instagram／Threads の気軽さと Spotify 的 “発見して聴く”
    体験を融合し、スピリチュアル領域のクリエイター経済を支援する。

  提供プラットフォーム:
    モバイル: [iOS, Android]
    デスクトップ(Web): [Chrome, Safari]
    Deep-Link:
      モバイル: "awakening://<path>"
      UniversalLink: "https://app.awakening.tld/<path>"
      対象: [投稿, プロフィール, イベント, ライブルーム, 商品, グループ]

機能要件:
  優先度タグ: {H: 高, M: 中, L: 低}

  ## ユーザー管理
  ユーザー管理:
    認証: {Google: true, Apple: true, Email+Passkey: true}
    アカウント設定:
      表示名: true
      プロフィール文: true
      プロフィール画像: true
      自己紹介音声: true
      外部リンクURL: true
      通知設定: [コメント, ハイライト, 新規フォロワー, ギフト提案]
    複数アカウント切替: {最大保持数: 5, UI: "プロフィール長押し"}

  ## フォロー
  フォロー機能:
    ファミリー: {理由入力必須: true, リスト公開: true}
    ウォッチ:   {理由不要: true, リスト公開: true}

  ## 投稿共通
  投稿共通設定:
    ハッシュタグ: {任意付与: true, 最大数/投稿: 5}
    後で見る(オフライン):
      対象: [音声, 画像, テキスト]
      端末保存: "暗号化キャッシュ(最大100件)"

  ## タイムライン
  タイムライン:
    投稿メディア:
      音声: {録音: true, アップロード: true}
      画像: {アップロード: true, GIF対応: true, AI生成: L}
      テキスト: {最大文字数: 10000, プレビュー: 280}
      動画: {現状サポート: false, 拡張余地: true}
    表示: {スクロール: "縦1列", デフォルト: "ファミリー"}
    アクション:
      いいね: true
      コメント: true
      ブックマーク: {保存先: "自分のみ"}
      ハイライト: {理由必須: true, 取消: false, 公開: true}
      後で見る: true
      シェアURL: true
    ミニオーディオプレーヤー: {UI要素: [アートワーク, タイトル, 再生/停止, シーク, 波形]}

  ## ストーリーズ
  ストーリーズ:
    メディア: "画像のみ"
    画像編集: [テキスト, スタンプ, 位置情報]
    再投稿: true

  ## ダイレクトメッセージ
  ダイレクトメッセージ:
    種類: [テキスト, 画像, 音声メモ]
    既読: true
    E2E暗号化: true

  ## AIチャット
  AIチャット:
    モデル: "Gemini-2.5-Pro"
    機能: [投稿/イベント/商品検索, 設定変更相談]
    コンテキスト保持: true
    ログ保存: 10y

  ## 検索
  検索:
    エンジン: "Supabase PG Full-Text"
    対象: [ユーザー, 投稿, ハッシュタグ]

  ## パーソナルAI
  パーソナルAIキュレーター:
    CRON: "毎朝5:00 JST"
    出力: "プレイリスト 5-10件"
  MyRadio:
    AI生成: true
    オフラインキャッシュ: true
  ヒットチャート: {カテゴリ: [総合Top50, 急上昇Top20]}

  ## イベント
  イベント:
    音声ワークショップ:
      ライブ: "ライブルーム(購入者限定)"
      アーカイブ: 自動
    決済: {Stripe, 手数料: 7%}

  ## ショップ
  ショップ:
    商品タイプ: ["物理商品", "オンラインセッション", "音声"]
    音声即時出品:
      投稿「出品」ボタン: true
      AI説明文生成: true
      プレビュー: "冒頭20-30秒"
      音質向上: 自動
    出品者管理: {取引一覧: true, 売上ダッシュボード: true}
    購入者管理: {注文履歴: true, 配送追跡: true}
    決済: "Stripe"
    光ギフト: {プリセット: [300, 600, 1200], 分配: {クリエイター: 92%, 手数料: 8%}}

  ## ライブルーム (H)
  ライブルーム:
    同時登壇: 10
    リスナー: "無制限"
    録音投稿化: 任意
    ルームチャット:
      リスナーコメント: true
      ホスト固定メッセージ: true
      URLシェア: true          # 外部/内部リンクを投稿可
      ピン機能: true
    Deep-Link生成:
      例: "awakening://room/<id>" (UniversalLink 同等)
    プロトコル: "WebRTC(LiveKit)"

  ## グループ
  グループ機能:
    上限: 100
    参加タイプ: ["無料", "月額サブスク"]
    チャット: [テキスト, 画像, 音声メモ]
    グループTL: true

  ## 日程調整, サブスク, クラファン, イマジネーション
  日程調整アシスト: L
  サブスク(スタンプ): L
  クラウドファンディング: L
  イマジネーション: L

非機能要件:
  パフォーマンス: {同時接続: 1000, TL応答(p95): "≤2s"}
  可用性: {SLA: "99.9%/月", RPO: "≤5min", RTO: "≤30min"}
  セキュリティ: {TLS: "1.3", Encryption: "AES-256", WebAuthn: true}
  オフライン:
    iOS/Android: {保存上限: "500 MB", 対象: ["後で見る", "MyRadio"]}
    Web: "非対応"
  Deep-Link:
    Scheme: "awakening://"
    UniversalLink: "https://app.awakening.tld/"
    Fallback: "ブラウザ → ストア誘導"
  アクセシビリティ: "WCAG 2.1 AA"
  国際化: ["ja", "en"]
  観測性: {Logs: "Loki 90d", Metrics: "Prometheus", Trace: "OTel"}
  CI/CD: {GitHub Actions→Supabase Edge, カバレッジ≥80%}

インフラ構成:
  ストレージ: {B2+Cloudflare, Supabase PG}
  EdgeFunctions(Deno): [画像変換, Waveform, AudioEnhance]
  LiveKit Cloud, Cloudflare TURN
  Stripe Webhook → gift_webhook
  Deep-Link Resolver: Supabase Edge Function (redirect)

開発運用:
  GitFlow, vitest, Vibe Coding(AI), Storybook+OpenAPI